import { IconType } from "react-icons";
import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
} from "react-icons/fa6";
import { GoDotFill } from "react-icons/go";
import { HiDownload } from "react-icons/hi";
import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";
import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
  PiNuclearPlantDuotone,
} from "react-icons/pi";
import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiReact,
  SiVite,
  SiTailwindcss,
  SiVuedotjs,
  SiAngular,
  SiFlutter,
  SiNodedotjs,
  SiPhp,
  SiLaravel,
  SiMysql,
  SiPostgresql,
  SiGit,
  SiLinux,
  SiDocker,
  SiRedhatopenshift,
  SiBamboo,
  SiCanva,
} from "react-icons/si";
import { TbBrandGolang, TbBrandReactNative } from "react-icons/tb";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  download: HiDownload,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  lab: PiNuclearPlantDuotone,
  dot: GoDotFill,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  react: SiReact,
  vue: SiVuedotjs,
  angular: SiAngular,
  vite: SiVite,
  tailwindcss: SiTailwindcss,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  reactnative: TbBrandReactNative,
  flutter: SiFlutter,
  golang: TbBrandGolang,
  nodejs: SiNodedotjs,
  php: SiPhp,
  laravel: SiLaravel,
  mysql: SiMysql,
  postgresql: SiPostgresql,
  git: SiGit,
  linux: SiLinux,
  docker: SiDocker,
  openshift: SiRedhatopenshift,
  bamboo: SiBamboo,
  supabase: SiSupabase,
  figma: SiFigma,
  canva: SiCanva,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
